# Generated by Django 4.1.11 on 2023-11-27 05:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("athanor", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="playviewdb",
            name="db_cmdset_storage",
            field=models.CharField(
                blank=True,
                help_text="optional python path to a cmdset class.",
                max_length=255,
                null=True,
                verbose_name="cmdset",
            ),
        ),
    ]
