CHARACTERS_ONLINE = set()

CMDSETS_UNLOGGEDIN_EXTRA = []
CMDSETS_SESSION_EXTRA = []
CMDSETS_CHARACTER_EXTRA = []
CMDSETS_ACCOUNT_EXTRA = []

CMD_MODULES_UNLOGGEDIN = []
CMD_MODULES_SESSION = []
CMD_MODULES_CHARACTER = []
CMD_MODULES_ACCOUNT = []